Repository nspcc-dev/neo-go, pull requests merged in 2019-11, with the labels that each got.

#471 Minor RPC fixes
  pkg/rpc/server.go
  pkg/rpc/server_test.go
Labels: rpc

#462 vm: restrict total stack item count
  pkg/vm/stack.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: vm

#478 Handshake and peers fix
  config/config.go
  config/protocol.mainnet.yml
  config/protocol.privnet.docker.four.yml
  config/protocol.privnet.docker.one.yml
  config/protocol.privnet.docker.three.yml
  config/protocol.privnet.docker.two.yml
  config/protocol.privnet.yml
  config/protocol.testnet.yml
  config/protocol.unit_testnet.yml
  pkg/network/handshakestage_string.go
  pkg/network/helper_test.go
  pkg/network/peer.go
  pkg/network/server.go
  pkg/network/server_config.go
  pkg/network/server_test.go
  pkg/network/tcp_peer.go
  pkg/network/tcp_peer_test.go
  pkg/rpc/server.go
Labels: node

#480 network: wait for both Version messages before ACKing
  pkg/network/tcp_peer.go
  pkg/network/tcp_peer_test.go
Labels: node

#496 vm: fix a bug in collection serialize
  pkg/vm/serialization.go
  pkg/vm/vm_test.go
Labels: bug, vm

#505 io: restrict ReadArray max array size
  pkg/io/binaryReader.go
  pkg/io/binaryrw_test.go
Labels: bug

#506 network: write messages atomically
  pkg/network/tcp_peer.go
Labels: bug

#511 Contract deployment
  cli/smartcontract/smart_contract.go
  pkg/core/account_state.go
  pkg/core/blockchain.go
  pkg/core/transaction/invocation.go
  pkg/core/transaction/transaction_test.go
  pkg/rpc/client.go
  pkg/rpc/doc.go
  pkg/rpc/neoScanBalanceGetter.go
  pkg/rpc/neoScanTypes.go
  pkg/rpc/rpc.go
  pkg/rpc/scdetails.go
  pkg/rpc/stack_param.go
  pkg/rpc/txBuilder.go
  pkg/rpc/types.go
Labels: rpc, smartContract

#513 rpc: extend param unmarshaling
  pkg/rpc/client.go
  pkg/rpc/param.go
  pkg/rpc/param_test.go
  pkg/rpc/params.go
  pkg/rpc/server.go
  pkg/rpc/server_test.go
  pkg/rpc/stack_param_test.go
Labels: rpc, test

#515 util: add missing tests
  pkg/util/array_test.go
  pkg/util/fixed8_test.go
  pkg/util/uint160_test.go
  pkg/util/uint256_test.go
Labels: test

#523 Fix interim block changes store
  pkg/core/blockchain.go
  pkg/core/blockchain_state.go
Labels: bug, node

#507 network: plug in dBFT library
  .docker/docker-compose.yml
  Makefile
  config/config.go
  config/protocol.privnet.docker.four.yml
  go.mod
  go.sum
  pkg/consensus/block.go
  pkg/consensus/block_test.go
  pkg/consensus/cache.go
  pkg/consensus/cache_test.go
  pkg/consensus/change_view.go
  pkg/consensus/change_view_test.go
  pkg/consensus/commit.go
  pkg/consensus/commit_test.go
  pkg/consensus/consensus.go
  pkg/consensus/crypto.go
  pkg/consensus/crypto_test.go
  pkg/consensus/logger.go
  pkg/consensus/payload.go
  pkg/consensus/payload_test.go
  pkg/consensus/prepare_request.go
  pkg/consensus/prepare_request_test.go
  pkg/consensus/prepare_response.go
  pkg/consensus/prepare_response_test.go
  pkg/consensus/recovery_message.go
  pkg/consensus/recovery_request.go
  pkg/consensus/recovery_request_test.go
  pkg/core/block_base.go
  pkg/core/helper_test.go
  pkg/network/server.go
  pkg/network/server_config.go
  pkg/wallet/account.go
Labels: consensus, node

#525 docs: add consensus.md
  README.md
  docs/consensus.md
Labels: documentation

#516 crypto: add more test for error cases
  pkg/crypto/hash/hash_test.go
  pkg/crypto/keys/nep2_test.go
  pkg/crypto/keys/private_key_test.go
  pkg/crypto/keys/publickey_test.go
  pkg/crypto/keys/sign_verify_test.go
  pkg/crypto/keys/wif_test.go
  pkg/internal/keytestcases/testcases.go
  pkg/wallet/account_test.go
Labels: test

#527 Invoke RPC
  cli/smartcontract/smart_contract.go
  docs/rpc.md
  pkg/rpc/server.go
  pkg/rpc/server_test.go
  pkg/rpc/txBuilder.go
Labels: rpc

#528 consensus: fix 2 bugs
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
Labels: bug

#529 Peer communication fixes
  .docker/6000-privnet-blocks.acc.gz
  .docker/docker-compose.yml
  .docker/privnet-entrypoint.sh
  Dockerfile
  Makefile
  config/protocol.privnet.docker.four.yml
  config/protocol.privnet.docker.one.yml
  config/protocol.privnet.docker.three.yml
  config/protocol.privnet.docker.two.yml
  pkg/consensus/consensus.go
  pkg/core/blockchain.go
  pkg/network/payload/headers.go
  pkg/network/server.go
  pkg/network/tcp_transport.go
Labels: bug, node

#530 docs: update consensus doc with more details
  docs/consensus.md
Labels: documentation
