Repository nspcc-dev/neo-go, pull requests merged in 2019-10, with the labels that each got.

#432 Disconnection fixes
  pkg/network/message.go
  pkg/network/server.go
  pkg/network/server_test.go
Labels: protocol

#427 Implement limitations on maximum collection size
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: VM

#435 Restrict max item size on stack
  pkg/vm/context.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: VM

#438 vm: copy slice in NEWARRAY/NEWSTRUCT
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: Bug, VM

#442 vm: fix tests failing, follow-up to #426
  pkg/vm/vm.go
Labels: VM

#451 vm: implement stack isolation opcodes, fix #192
  pkg/vm/context.go
  pkg/vm/instruction_string.go
  pkg/vm/instructions.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: vm

#461 vm: restrict max invocation stack size
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: vm
