Repository nspcc-dev/neo-go, pull requests merged in 2019-12, with the labels that each got.

#533 network: rework inventory handling, check for item presence
  pkg/network/server.go
Labels: node

#532 network: count only handshaked peers as connected
  pkg/consensus/recovery_message.go
  pkg/consensus/recovery_message_test.go
  pkg/network/server.go
Labels: consensus, node

#535 Mempool locking fixes
  pkg/core/mem_pool.go
Labels: node

#538 Opcodes and related
  .gitignore
  cli/smartcontract/smart_contract.go
  docs/cli.md
  pkg/compiler/analysis.go
  pkg/compiler/codegen.go
  pkg/compiler/compiler.go
  pkg/compiler/compiler_test.go
  pkg/compiler/emit.go
  pkg/compiler/func_scope.go
  pkg/compiler/syscall.go
  pkg/consensus/consensus.go
  pkg/consensus/payload.go
  pkg/core/helper_test.go
  pkg/core/interop_system.go
  pkg/core/util.go
  pkg/crypto/keys/publickey.go
  pkg/crypto/keys/wif.go
  pkg/rpc/txBuilder.go
  pkg/smartcontract/contract.go
  pkg/smartcontract/contract_test.go
  pkg/vm/cli/cli.go
  pkg/vm/context.go
  pkg/vm/contract_checks.go
  pkg/vm/contract_checks_test.go
  pkg/vm/emit.go
  pkg/vm/emit_test.go
  pkg/vm/instruction_string.go
  pkg/vm/instructions.go
  pkg/vm/json_test.go
  pkg/vm/opcode/opcode.go
  pkg/vm/opcode/opcode_string.go
  pkg/vm/opcode/opcode_test.go
  pkg/vm/tests/vm_test.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: vm

#544 consensus: sign and verify consensus payloads
  go.mod
  go.sum
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/consensus/recovery_message.go
  pkg/consensus/recovery_message_test.go
Labels: consensus

#558 Some VM instructions optimization
  pkg/vm/stack.go
  pkg/vm/stack_test.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: vm

#561 Fix duping and add tests
  pkg/vm/context.go
  pkg/vm/stack.go
  pkg/vm/stack_item.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: bug

#566 compiler: implement assignment to a variable index
  pkg/compiler/codegen.go
  pkg/vm/tests/slice_test.go
Labels: compiler

#559 vm: don't refcount simple items
  pkg/vm/stack.go
Labels: vm

#571 compiler: move tests from vm/tests
  pkg/compiler/assign_test.go
  pkg/compiler/binary_expr_test.go
  pkg/compiler/byte_conversion_test.go
  pkg/compiler/constant_test.go
  pkg/compiler/for_test.go
  pkg/compiler/function_call_test.go
  pkg/compiler/if_test.go
  pkg/compiler/import_test.go
  pkg/compiler/numeric_test.go
  pkg/compiler/slice_test.go
  pkg/compiler/struct_test.go
  pkg/compiler/syscall_test.go
  pkg/compiler/testdata/bar/bar.go
  pkg/compiler/testdata/foo/foo.go
  pkg/compiler/testdata/foobar/bar.go
  pkg/compiler/testdata/foobar/foo.go
  pkg/compiler/type_test.go
  pkg/compiler/util_test.go
  pkg/compiler/vm_test.go
Labels: compiler, test

#574 compiler: implement multiple return support
  pkg/compiler/codegen.go
  pkg/compiler/return_test.go
Labels: compiler

#578 consensus: verify payloads correctly
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/consensus/payload.go
  pkg/consensus/payload_test.go
  pkg/consensus/recovery_message_test.go
  pkg/core/blockchain.go
  pkg/core/blockchain_test.go
Labels: consensus

#581 core: implement Neo.Storage.Find interop
  pkg/core/interop_neo.go
  pkg/core/interop_neo_test.go
  pkg/core/interops.go
  pkg/core/interops_test.go
  pkg/vm/interop.go
Labels: vm

#582 DB dump and restore fixes
  cli/server/server.go
Labels: bug

#583 consensus: return nil interface from getTx
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
Labels: consensus
