Repository nspcc-dev/neo-go, pull requests merged in 2019-09, with the labels that each got.

#354 Some VM opcodes and fixes
  pkg/vm/stack.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: VM

#358 _pkg.dev: drop vm
  _pkg.dev/vm/stack/Int.go
  _pkg.dev/vm/stack/Readme.md
  _pkg.dev/vm/stack/array.go
  _pkg.dev/vm/stack/array_test.go
  _pkg.dev/vm/stack/boolean.go
  _pkg.dev/vm/stack/builder.go
  _pkg.dev/vm/stack/bytearray.go
  _pkg.dev/vm/stack/context.go
  _pkg.dev/vm/stack/instruction.go
  _pkg.dev/vm/stack/int_test.go
  _pkg.dev/vm/stack/invocationstack.go
  _pkg.dev/vm/stack/map.go
  _pkg.dev/vm/stack/map_test.go
  _pkg.dev/vm/stack/stack.go
  _pkg.dev/vm/stack/stack_test.go
  _pkg.dev/vm/stack/stackitem.go
  _pkg.dev/vm/stack/stackitem_test.go
  _pkg.dev/vm/stack/test_helper.go
  _pkg.dev/vm/state.go
  _pkg.dev/vm/vm.go
  _pkg.dev/vm/vm_ops.go
  _pkg.dev/vm/vm_ops_bitwise.go
  _pkg.dev/vm/vm_ops_bitwise_test.go
  _pkg.dev/vm/vm_ops_exceptions.go
  _pkg.dev/vm/vm_ops_flow.go
  _pkg.dev/vm/vm_ops_flow_test.go
  _pkg.dev/vm/vm_ops_maths.go
  _pkg.dev/vm/vm_ops_maths_test.go
  _pkg.dev/vm/vm_ops_stackmani.go
  _pkg.dev/vm/vm_ops_stackmani_test.go
  _pkg.dev/vm/vm_test.go
  _pkg.dev/vm/vmopscrypto.go
  _pkg.dev/vm/vmopscrypto_test.go
Labels: VM

#360 vm: implement Array <-> Struct conversion
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: VM

#386 update minimum supported version of Go to 1.12
  .circleci/config.yml
  .travis.yml
  README.md
Labels: go

#404 Move user docs
  README.md
  ROADMAP.md
  docs/cli.md
  docs/compiler.md
  docs/rpc.md
  docs/vm.md
  pkg/core/storage/README.md
  pkg/rpc/README.md
  pkg/rpc/doc.go
Labels: documentation

#405 VM: compare Array by reference
  pkg/vm/stack_item.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: VM

#406 VM: do not pop too many items from stack
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: VM
