Repository nspcc-dev/neo-go, pull requests merged in 2020-06, with the labels that each got.

#990 Initial MPT implementation (2.x)
  cli/server/dump.go
  pkg/core/mpt/branch.go
  pkg/core/mpt/doc.go
  pkg/core/mpt/extension.go
  pkg/core/mpt/hash.go
  pkg/core/mpt/helpers.go
  pkg/core/mpt/helpers_test.go
  pkg/core/mpt/leaf.go
  pkg/core/mpt/node.go
  pkg/core/mpt/node_test.go
  pkg/core/mpt/proof.go
  pkg/core/mpt/proof_test.go
  pkg/core/mpt/trie.go
  pkg/core/mpt/trie_test.go
  pkg/core/storage/store.go
Labels: feature

#1007 consensus: update dbft to include CountFailed and RecoveryMessage changes
  go.mod
  go.sum
  pkg/consensus/block.go
  pkg/consensus/block_test.go
  pkg/consensus/consensus.go
  pkg/consensus/prepare_request.go
  pkg/consensus/prepare_request_test.go
Labels: consensus

#1008 core: update MPT during block processing
  pkg/consensus/commit.go
  pkg/consensus/consensus.go
  pkg/consensus/prepare_request.go
  pkg/core/blockchain.go
  pkg/core/blockchainer.go
  pkg/core/dao/dao.go
  pkg/core/mpt/helpers.go
  pkg/core/state/mpt_root.go
  pkg/core/state/mpt_root_test.go
  pkg/network/helper_test.go
  pkg/network/message.go
  pkg/network/payload/inventory.go
  pkg/network/payload/state_root.go
  pkg/network/payload/state_root_test.go
  pkg/network/server.go
Labels: feature

#1010 update dbft to include CountFailed and RecoveryMessage changes
  go.mod
  go.sum
Labels: consensus

#1009 consensus: update dbft to include CountFailed and RecoveryMessage changes
  go.mod
  go.sum
  pkg/consensus/block.go
  pkg/consensus/block_test.go
  pkg/consensus/consensus.go
  pkg/consensus/prepare_request.go
  pkg/consensus/prepare_request_test.go
Labels: consensus

#1017 compiler: add recover interops
  pkg/compiler/syscall.go
  pkg/interop/crypto/crypto.go
Labels: compiler

#1015 Use base64 in JSON
  pkg/core/transaction/transaction.go
  pkg/core/transaction/witness.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/client/wsclient_test.go
  pkg/rpc/response/result/contract_state.go
  pkg/smartcontract/parameter.go
  pkg/smartcontract/parameter_test.go
Labels: rpc

#1013 vm: move StackItem to a separate package
  pkg/compiler/codegen.go
  pkg/compiler/for_test.go
  pkg/compiler/slice_test.go
  pkg/compiler/struct_test.go
  pkg/compiler/syscall_test.go
  pkg/compiler/vm_test.go
  pkg/core/blockchain.go
  pkg/core/interop/context.go
  pkg/core/interop/crypto/ecdsa.go
  pkg/core/interop/crypto/ecdsa_test.go
  pkg/core/interop_neo.go
  pkg/core/interop_neo_test.go
  pkg/core/interop_system.go
  pkg/core/native/native_neo.go
  pkg/core/native/native_nep5.go
  pkg/core/native/validators_count.go
  pkg/core/native_contract_test.go
  pkg/core/state/native_state.go
  pkg/core/state/notification_event.go
  pkg/core/state/notification_event_test.go
  pkg/encoding/bigint/bigint.go
  pkg/encoding/bigint/bigint_test.go
  pkg/rpc/client/nep5.go
  pkg/rpc/response/result/application_log.go
  pkg/rpc/server/server.go
  pkg/smartcontract/convertor.go
  pkg/smartcontract/convertor_test.go
  pkg/vm/cli/cli.go
  pkg/vm/context.go
  pkg/vm/contract_checks.go
  pkg/vm/emit/emit.go
  pkg/vm/emit/emit_test.go
  pkg/vm/interop.go
  pkg/vm/interop_iterators.go
  pkg/vm/json_test.go
  pkg/vm/ref_counter.go
  pkg/vm/ref_counter_test.go
  pkg/vm/serialization.go
  pkg/vm/slot.go
  pkg/vm/slot_test.go
  pkg/vm/stack.go
  pkg/vm/stack_item.go
  pkg/vm/stack_item_test.go
  pkg/vm/stack_test.go
  pkg/vm/stackitem/item.go
  pkg/vm/stackitem/item_test.go
  pkg/vm/stackitem/serialization.go
  pkg/vm/stackitem/type.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: vm

#1024 compiler: process interop together with package
  pkg/compiler/analysis.go
  pkg/compiler/codegen.go
  pkg/compiler/func_scope.go
  pkg/compiler/interop_test.go
  pkg/compiler/testdata/block/block.go
  pkg/compiler/testdata/util/equals.go
Labels: bug, compiler

#1012 rpc: implement MPT-related RPC (2.x)
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/core/blockchain.go
  pkg/core/blockchainer.go
  pkg/core/cache/cache.go
  pkg/core/cache/cache_test.go
  pkg/core/state/mpt_root.go
  pkg/core/state/mpt_root_test.go
  pkg/network/helper_test.go
  pkg/network/server.go
  pkg/rpc/client/wsclient_test.go
  pkg/rpc/request/param.go
  pkg/rpc/request/param_test.go
  pkg/rpc/request/params.go
  pkg/rpc/response/result/mpt.go
  pkg/rpc/response/result/mpt_test.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
Labels: feature, rpc

#1034 *: implement System.Blockchain.GetTransaction and System.Blockchain.GetBlock interops
  pkg/compiler/codegen.go
  pkg/compiler/syscall.go
  pkg/core/gas_price.go
  pkg/core/interop_neo.go
  pkg/core/interop_neo_test.go
  pkg/core/interop_system.go
  pkg/core/interop_system_test.go
  pkg/core/interops.go
  pkg/core/interops_test.go
  pkg/interop/attribute/attribute.go
  pkg/interop/block/block.go
  pkg/interop/blockchain/blockchain.go
  pkg/interop/engine/engine.go
  pkg/interop/transaction/transaction.go
Labels: neo3

#1039 rpc: update `getversion` RPC-call
  pkg/network/server.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/response/result/version.go
  pkg/rpc/server/server.go
Labels: neo3, rpc

#1021 compiler: implement Remove builtin (2.x)
  pkg/compiler/analysis.go
  pkg/compiler/codegen.go
  pkg/compiler/interop_test.go
  pkg/interop/util/util.go
Labels: compiler, feature

#1041 Consensus fixes 2.x neox
  go.mod
  go.sum
  pkg/consensus/recovery_message.go
Labels: consensus

#1033 Add Manifest to state.Contract
  cli/smartcontract/smart_contract.go
  pkg/compiler/compiler.go
  pkg/compiler/debug.go
  pkg/compiler/debug_test.go
  pkg/compiler/syscall.go
  pkg/core/dao/cacheddao_test.go
  pkg/core/dao/dao.go
  pkg/core/dao/dao_test.go
  pkg/core/gas_price.go
  pkg/core/gas_price_test.go
  pkg/core/helper_test.go
  pkg/core/interop/context.go
  pkg/core/interop/runtime/witness.go
  pkg/core/interop_neo.go
  pkg/core/interop_neo_test.go
  pkg/core/interop_system.go
  pkg/core/interops.go
  pkg/core/interops_test.go
  pkg/core/native/interop.go
  pkg/core/native/native_gas.go
  pkg/core/native/native_neo.go
  pkg/core/state/contract.go
  pkg/core/state/contract_test.go
  pkg/core/storage/store.go
  pkg/interop/contract/contract.go
  pkg/rpc/client/rpc.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/request/txBuilder.go
  pkg/rpc/response/result/contract_state.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/testblocks.acc
  pkg/smartcontract/deployment_price.go
  pkg/smartcontract/manifest/manifest.go
  pkg/smartcontract/parameter.go
  pkg/vm/context.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: feature, neo3

#1045 consensus: verify state root in PrepareRequest
  go.mod
  go.sum
  pkg/consensus/consensus.go
Labels: bug

#1044 Provide required call flags and allowed triggers in interop descriptions.
  pkg/compiler/interop_test.go
  pkg/core/blockchain.go
  pkg/core/interop/context.go
  pkg/core/interop_neo.go
  pkg/core/interop_system.go
  pkg/core/interops.go
  pkg/core/native/contract.go
  pkg/core/native/native_neo.go
  pkg/core/native/native_nep5.go
  pkg/rpc/server/server.go
  pkg/smartcontract/call_flags.go
  pkg/smartcontract/call_flags_test.go
  pkg/smartcontract/trigger/trigger_type.go
  pkg/smartcontract/trigger/trigger_type_string.go
  pkg/smartcontract/trigger/trigger_type_test.go
  pkg/vm/context.go
  pkg/vm/interop.go
  pkg/vm/json_test.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: neo3

#952 compiler: set default values for complex struct fields (2.x)
  pkg/compiler/analysis.go
  pkg/compiler/codegen.go
  pkg/compiler/debug.go
  pkg/compiler/slice_test.go
  pkg/compiler/struct_test.go
Labels: bug, compiler

#1047 rpc: update invoke* RPC-calls
  cli/smartcontract/smart_contract.go
  pkg/core/blockchain.go
  pkg/core/blockchainer/blockchainer.go
  pkg/core/transaction/witness_scope.go
  pkg/core/transaction/witness_scope_test.go
  pkg/network/helper_test.go
  pkg/rpc/client/nep5.go
  pkg/rpc/client/rpc.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/request/param.go
  pkg/rpc/request/param_test.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/test_verify.avm
  pkg/rpc/server/testdata/test_verify.go
Labels: neo3, rpc

#1050 core: adjust storage syscalls
  pkg/core/gas_price.go
  pkg/core/gas_price_test.go
  pkg/core/interop_neo.go
  pkg/core/interop_system.go
  pkg/core/interops.go
Labels: neo3

#1051 core: add json marshaller for Cosigner's scopes
  pkg/core/transaction/witness_scope.go
  pkg/core/transaction/witness_scope_string.go
  pkg/core/transaction/witness_scope_test.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/client/wsclient_test.go
  pkg/rpc/request/param_test.go
Labels: neo3, rpc

#1053 Adjust prices for binary/enumerator/iterator syscalls
  pkg/compiler/syscall.go
  pkg/core/interops.go
  pkg/interop/binary/binary.go
  pkg/interop/runtime/runtime.go
  pkg/vm/interop.go
  pkg/vm/vm_test.go
Labels: neo3, vm

#1048 Implement System.Json.* interops
  pkg/compiler/assign_test.go
  pkg/compiler/syscall.go
  pkg/core/interop/json/json.go
  pkg/core/interop/json/json_test.go
  pkg/core/interops.go
  pkg/interop/json/json.go
  pkg/vm/context.go
  pkg/vm/contract_checks.go
  pkg/vm/interop.go
  pkg/vm/stackitem/item.go
  pkg/vm/stackitem/json.go
  pkg/vm/stackitem/json_test.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: feature, neo3, vm

#1054 Adjust contract/blockchain syscalls
  pkg/core/interop_system.go
  pkg/core/interop_system_test.go
  pkg/core/interops.go
Labels: neo3

#1056 Adjust runtime syscalls to NEO3
  examples/engine/engine.go
  examples/token/nep5/nep5.go
  pkg/compiler/codegen.go
  pkg/compiler/syscall.go
  pkg/core/blockchain.go
  pkg/core/interop/context.go
  pkg/core/interop/runtime/util.go
  pkg/core/interop_system.go
  pkg/core/interop_system_test.go
  pkg/core/interops.go
  pkg/interop/contract/contract.go
  pkg/interop/engine/engine.go
  pkg/interop/runtime/engine.go
  pkg/interop/runtime/runtime.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/test_contract.avm
  pkg/rpc/server/testdata/test_contract.go
  pkg/rpc/server/testdata/testblocks.acc
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: neo3

#1057 Update addresses to NEO3 format
  .docker/wallets/wallet1.json
  .docker/wallets/wallet1_solo.json
  .docker/wallets/wallet2.json
  .docker/wallets/wallet3.json
  .docker/wallets/wallet4.json
  cli/server/server.go
  cli/wallet/wallet.go
  config/protocol.mainnet.yml
  config/protocol.privnet.docker.four.yml
  config/protocol.privnet.docker.one.yml
  config/protocol.privnet.docker.single.yml
  config/protocol.privnet.docker.three.yml
  config/protocol.privnet.docker.two.yml
  config/protocol.privnet.yml
  config/protocol.testnet.yml
  config/protocol.unit_testnet.yml
  docs/cli.md
  examples/runtime/runtime.go
  examples/token-sale/token_sale.go
  examples/token/token.go
  pkg/compiler/interop_test.go
  pkg/config/protocol_config.go
  pkg/consensus/testdata/wallet1.json
  pkg/consensus/testdata/wallet2.json
  pkg/consensus/testdata/wallet3.json
  pkg/consensus/testdata/wallet4.json
  pkg/core/util_test.go
  pkg/crypto/keys/publickey_test.go
  pkg/encoding/address/address.go
  pkg/encoding/address/address_test.go
  pkg/internal/keytestcases/testcases.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/client/wsclient_test.go
  pkg/rpc/request/param_test.go
  pkg/rpc/server/server_test.go
  pkg/smartcontract/param_type_test.go
  pkg/wallet/account_test.go
  pkg/wallet/testdata/wallet1.json
  pkg/wallet/testdata/wallet2.json
  pkg/wallet/token_test.go
  pkg/wallet/wallet.go
  pkg/wallet/wallet_test.go
Labels: neo3

#1065 core,native: persist native contract via VM
  pkg/core/blockchain.go
  pkg/core/blockchain_test.go
  pkg/core/interop/context.go
  pkg/core/native/contract.go
  pkg/core/native/native_gas.go
  pkg/core/native/native_neo.go
  pkg/core/native/native_nep5.go
  pkg/core/native_contract_test.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/subscription_test.go
Labels: neo3

#1068 Remove logic related to free transactions
  config/protocol.mainnet.yml
  config/protocol.privnet.docker.four.yml
  config/protocol.privnet.docker.one.yml
  config/protocol.privnet.docker.single.yml
  config/protocol.privnet.docker.three.yml
  config/protocol.privnet.docker.two.yml
  config/protocol.privnet.yml
  config/protocol.testnet.yml
  config/protocol.unit_testnet.yml
  pkg/config/protocol_config.go
  pkg/consensus/consensus_test.go
  pkg/core/blockchain.go
  pkg/core/mempool/feer.go
  pkg/core/mempool/mem_pool.go
  pkg/core/mempool/mem_pool_test.go
  pkg/core/native_contract_test.go
  pkg/network/helper_test.go
  pkg/rpc/server/server_helper_test.go
Labels: neo3

#1070 Update `getapplicationlog` RPC
  pkg/core/blockchain.go
  pkg/core/native/contract.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/client/wsclient_test.go
  pkg/rpc/response/result/application_log.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/subscription.go
  pkg/rpc/server/subscription_test.go
  pkg/smartcontract/param_type.go
  pkg/smartcontract/parameter.go
  pkg/vm/stackitem/serialization.go
Labels: neo3

#1076 Fix interop gas prices
  pkg/core/interop/crypto/ecdsa.go
  pkg/core/interops.go
  pkg/core/native/native_nep5.go
  pkg/vm/interop.go
Labels: bug

#1072 Allow NullPayload only for CMDGetAddr
  pkg/network/message.go
  pkg/network/payload/payload.go
Labels: bug, neo3

#1077 core: store smartcontract items by id
  pkg/core/blockchain.go
  pkg/core/blockchainer/blockchainer.go
  pkg/core/dao/cacheddao_test.go
  pkg/core/dao/dao.go
  pkg/core/dao/dao_test.go
  pkg/core/interop_neo.go
  pkg/core/interop_neo_test.go
  pkg/core/interop_system.go
  pkg/core/native/native_neo.go
  pkg/core/native/native_nep5.go
  pkg/network/helper_test.go
  pkg/rpc/server/server.go
Labels: neo3, smartContract

#1080 message: fix Verack processsing
  pkg/network/message.go
Labels: bug

#1086 consensus: fix commitCompact payload
  pkg/consensus/payload_test.go
  pkg/consensus/recovery_message.go
Labels: bug

#1079 Implement for-range loop without iterators
  pkg/compiler/codegen.go
Labels: compiler, feature

#1087 Allow to restrict slice size in `io.ReadVarBytes()`
  pkg/consensus/recovery_message.go
  pkg/io/binaryReader.go
  pkg/io/binaryrw_test.go
Labels: bug

#1091 rpc: add GetStorageByID RPC client method
  pkg/rpc/client/rpc.go
  pkg/rpc/client/rpc_test.go
Labels: neo3, rpc

#1058 core: add native policy contract
  config/protocol.mainnet.yml
  config/protocol.testnet.yml
  go.mod
  go.sum
  pkg/config/protocol_config.go
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/core/blockchain.go
  pkg/core/helper_test.go
  pkg/core/mempool/mem_pool.go
  pkg/core/native/blocked_accounts.go
  pkg/core/native/blocked_accounts_test.go
  pkg/core/native/contract.go
  pkg/core/native/policy.go
  pkg/core/native_policy_test.go
  pkg/network/compress.go
  pkg/network/message.go
  pkg/network/payload/payload.go
  pkg/rpc/client/policy.go
  pkg/rpc/client/rpc.go
  pkg/rpc/client/rpc_test.go
  pkg/smartcontract/parameter.go
  pkg/smartcontract/parameter_test.go
Labels: neo3

#1078 network: implement CMDMempool command
  pkg/network/server.go
Labels: feature, neo3

#1100 compiler: update debug.json format
  pkg/compiler/codegen.go
  pkg/compiler/compiler.go
  pkg/compiler/debug.go
  pkg/compiler/debug_test.go
Labels: compiler, neo3

#1103 Allow to omit types and struct field names in contracts
  pkg/compiler/codegen.go
  pkg/compiler/slice_test.go
  pkg/compiler/struct_test.go
Labels: compiler, feature

#1099 native: cache GetValidators result
  pkg/core/native/native_neo.go
Labels: feature, neo3

#1105 interop: fix key recovery functions documentation
  pkg/interop/crypto/crypto.go
Labels: documentation

#1106 Add missing neox rpc client wrappers
  pkg/rpc/client/rpc_test.go
  pkg/rpc/client/state.go
  pkg/rpc/server/server_test.go
Labels: rpc

#1104 Fix `wallet nep5 transfer` command
  cli/wallet/multisig.go
  cli/wallet/nep5.go
  cli/wallet/wallet.go
  docs/cli.md
  pkg/consensus/consensus.go
  pkg/rpc/client/nep5.go
  pkg/rpc/client/rpc.go
Labels: bug

#1109 docs: add neox documentation
  README.md
  docs/neox.md
Labels: documentation

#1101 Support type conversions
  pkg/compiler/codegen.go
  pkg/compiler/convert_test.go
  pkg/compiler/types.go
Labels: compiler, feature

#1112 cli: update wallet path argument name in cli context
  cli/wallet/multisig.go
  cli/wallet/nep5.go
  cli/wallet/wallet.go
Labels: bug

#1114 Fix test failures 2.x
  pkg/core/blockchain_test.go
  pkg/rpc/server/server.go
Labels: bug, test

#1113 Fix test failures
  pkg/core/blockchain_test.go
  pkg/rpc/server/server.go
Labels: bug, test

#1116 consensus: prevent synchronization stalls
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/core/cache/cache_test.go
Labels: consensus

#1120 cli: update hardcoded script hashes for neo and gas contracts
  pkg/rpc/client/nep5.go
Labels: bug

#1122 Extend PrintOps for JMP* and INIT* instructions
  pkg/vm/vm.go
Labels: vm

#1118 Support variadic functions in compiler
  pkg/compiler/codegen.go
  pkg/compiler/func_scope.go
  pkg/compiler/function_call_test.go
Labels: compiler, feature

#1123 compiler: support `...` variadic calls
  pkg/compiler/codegen.go
  pkg/compiler/function_call_test.go
Labels: compiler

#1125 Copy validators when returning to the outside
  pkg/consensus/consensus.go
  pkg/core/blockchain.go
  pkg/core/native/native_gas.go
  pkg/core/native/native_neo.go
  pkg/crypto/keys/publickey.go
  pkg/crypto/keys/publickey_test.go
  pkg/smartcontract/context/context_test.go
Labels: bug

#1129 consensus: take payload hash based on data
  pkg/consensus/consensus.go
  pkg/consensus/payload.go
Labels: bug

#1108 compiler: support *.nef and *.manifest.json generation
  cli/smartcontract/smart_contract.go
  docs/cli.md
  docs/compiler.md
  docs/vm.md
  pkg/compiler/compiler.go
  pkg/compiler/compiler_test.go
  pkg/compiler/debug.go
  pkg/compiler/debug_test.go
  pkg/config/application_config.go
  pkg/config/wallet_config.go
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/network/server_config.go
  pkg/smartcontract/nef/nef.go
  pkg/smartcontract/nef/nef_test.go
  pkg/vm/cli/cli.go
  pkg/vm/vm.go
Labels: compiler, neo3

#1132 *: switch from Fixed8 to int64
  cli/wallet/nep5.go
  pkg/consensus/consensus_test.go
  pkg/core/blockchain.go
  pkg/core/blockchainer/blockchainer.go
  pkg/core/gas_price.go
  pkg/core/helper_test.go
  pkg/core/interop/context.go
  pkg/core/interop/crypto/ecdsa.go
  pkg/core/interop/runtime/util.go
  pkg/core/interop_neo.go
  pkg/core/interop_system.go
  pkg/core/mempool/feer.go
  pkg/core/mempool/mem_pool.go
  pkg/core/mempool/mem_pool_test.go
  pkg/core/native/contract.go
  pkg/core/native/native_gas.go
  pkg/core/native/native_neo.go
  pkg/core/opcode_price.go
  pkg/core/state/notification_event.go
  pkg/core/transaction/transaction.go
  pkg/core/transaction/transaction_test.go
  pkg/core/util.go
  pkg/network/helper_test.go
  pkg/rpc/client/nep5.go
  pkg/rpc/client/rpc.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/client/wsclient_test.go
  pkg/rpc/request/txBuilder.go
  pkg/rpc/response/result/application_log.go
  pkg/rpc/response/result/invoke.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_helper_test.go
  pkg/rpc/server/server_test.go
  pkg/vm/interop.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: neo3

#1126 compiler: support variable shadowing
  pkg/compiler/codegen.go
  pkg/compiler/func_scope.go
  pkg/compiler/global_test.go
  pkg/compiler/vars.go
Labels: bug, compiler

#1136 consensus: prevent `invalid message` panic
  pkg/consensus/consensus.go
Labels: bug, consensus, neo3
