Repository nspcc-dev/neo-go, pull requests merged in 2020-10, with the labels that each got.

#1449 rpc: getvalidators -> getnextblockvalidators
  pkg/rpc/client/rpc.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
Labels: rpc

#1447 core: fix cache for (NEO).nextValidators and (NEO).committee
  pkg/core/blockchain.go
  pkg/core/native/contract.go
  pkg/core/native/native_gas.go
  pkg/core/native/native_neo.go
Labels: bug

#1458 core: calculate gas for `System.Storage.Put` correctly
  pkg/core/interop_system.go
  pkg/core/interop_system_test.go
Labels: bug

#1460 core: allow Null in `System.Contract.Update`
  pkg/core/interop_neo.go
  pkg/core/interop_system_test.go
  pkg/vm/stack.go
Labels: bug

#1452 Support `_deploy` method
  cli/contract_test.go
  cli/executor_test.go
  cli/testdata/deploy/main.go
  cli/testdata/deploy/neo-go.yml
  cli/testdata/deploy/sub/put.go
  cli/testdata/deploy/updated.go
  cli/wallet/validator.go
  docs/compiler.md
  pkg/compiler/analysis.go
  pkg/compiler/codegen.go
  pkg/compiler/debug.go
  pkg/compiler/debug_test.go
  pkg/compiler/func_scope.go
  pkg/compiler/init_test.go
  pkg/core/blockchain_test.go
  pkg/core/helper_test.go
  pkg/core/interop/contract/call.go
  pkg/core/interop_neo.go
  pkg/core/interop_system_test.go
  pkg/core/native/contract.go
  pkg/core/native/oracle.go
  pkg/core/native_designate_test.go
  pkg/core/native_oracle_test.go
  pkg/crypto/keys/publickey.go
  pkg/rpc/client/nep5.go
  pkg/rpc/request/txBuilder.go
  pkg/smartcontract/contract.go
  pkg/smartcontract/manifest/manifest.go
  pkg/vm/emit/emit.go
  pkg/vm/emit/emit_test.go
  pkg/vm/vm_test.go
Labels: compiler, test

#1464 vm: handle very big int creation properly
  pkg/vm/stackitem/item.go
  pkg/vm/stackitem/item_test.go
  pkg/vm/vm_test.go
Labels: vm

#1469 Fix protocol limits
  pkg/core/transaction/transaction.go
  pkg/core/transaction/witness.go
  pkg/core/transaction/witness_test.go
  pkg/network/payload/address.go
  pkg/network/payload/address_test.go
  pkg/network/payload/version.go
  pkg/network/server.go
  pkg/smartcontract/manifest/manifest.go
  pkg/smartcontract/nef/nef.go
  pkg/vm/stackitem/serialization.go
Labels: bug

#1480 core: drop stale transactions from the mempool
  pkg/core/blockchain.go
Labels: bug

#1487 storage: fix Get for BoltDB, fix #1482
  pkg/core/storage/boltdb_store.go
Labels: bug

#1488 compiler: fix manifest method offset
  pkg/compiler/codegen.go
  pkg/compiler/function_call_test.go
Labels: compiler

#1497 compiler: refactor void calls processing
  pkg/compiler/func_scope.go
  pkg/compiler/function_call_test.go
Labels: bug, compiler

#1489 rpc, cli: use base64 script encoding for Invoke* calls; add Magic to `getversion` RPC call
  cli/candidate_test.go
  cli/contract_test.go
  cli/multisig_test.go
  cli/nep5_test.go
  cli/options/options.go
  cli/options/options_test.go
  cli/smartcontract/smart_contract.go
  cli/wallet_test.go
  pkg/rpc/client/client.go
  pkg/rpc/client/doc_test.go
  pkg/rpc/client/nep5.go
  pkg/rpc/client/rpc.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/client/wsclient.go
  pkg/rpc/client/wsclient_test.go
  pkg/rpc/response/result/invoke.go
  pkg/rpc/response/result/version.go
  pkg/rpc/server/client_test.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
Labels: bug, rpc

#1502 cli: fixed removed network arguments
  cli/options/options.go
Labels: bug
