Repository nspcc-dev/neo-go, pull requests merged in 2020-04, with the labels that each got.

#810 config: move config.go out of config
  cli/main.go
  cli/server/server.go
  config/config.go
  integration/performance_test.go
  pkg/config/application_config.go
  pkg/config/config.go
  pkg/config/protocol_config.go
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/core/blockchain.go
  pkg/core/blockchainer.go
  pkg/core/helper_test.go
  pkg/core/util.go
  pkg/core/util_test.go
  pkg/network/helper_test.go
  pkg/network/message.go
  pkg/network/server_config.go
  pkg/rpc/rpc_config.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_helper_test.go
  pkg/wallet/wallet_config.go
Labels: refactoring

#816 Makefile: set config.Version properly
  Makefile
Labels: bug

#815 compiler: calculate stack size more precisely
  pkg/compiler/assign_test.go
  pkg/compiler/func_scope.go
Labels: compiler

#819 smartcontract: fix uint160 marshalling in smartcontract.Parameter
  pkg/smartcontract/parameter.go
  pkg/smartcontract/parameter_test.go
Labels: bug, rpc, smartContract

#826 vm: use truncated division in MOD
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: bug, vm

#825 compiler: accept varargs in `runtime.Notify`
  pkg/compiler/codegen.go
  pkg/compiler/syscall_test.go
  pkg/compiler/vm_test.go
  pkg/core/helper_test.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/test_contract.avm
  pkg/rpc/server/testdata/test_contract.go
  pkg/rpc/server/testdata/testblocks.acc
Labels: bug, compiler

#827 vm: handle negative arguments in SHL/SHR
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: bug, vm

#811 compiler: support neo-debugger
  cli/smartcontract/smart_contract.go
  pkg/compiler/codegen.go
  pkg/compiler/compiler.go
  pkg/compiler/debug.go
  pkg/compiler/debug_test.go
  pkg/compiler/func_scope.go
Labels: feature

#832 core: split into several packages
  pkg/core/blockchain.go
  pkg/core/blockchain_test.go
  pkg/core/dao/cacheddao.go
  pkg/core/dao/cacheddao_test.go
  pkg/core/dao/dao.go
  pkg/core/dao/dao_test.go
  pkg/core/gas_price_test.go
  pkg/core/interop_neo.go
  pkg/core/interop_neo_test.go
  pkg/core/interop_system.go
  pkg/core/interops.go
  pkg/core/interops_test.go
  pkg/core/uint32.go
Labels: refactoring

#829 cli: rename `contract compile` --debug flag
  cli/smartcontract/smart_contract.go
  pkg/compiler/compiler.go
Labels: bug

#833 vm: missing tests for CALL* instructions
  pkg/vm/vm_test.go
Labels: test, vm

#784 vm: support NULL stack item
  pkg/smartcontract/param_type.go
  pkg/vm/opcode/opcode.go
  pkg/vm/stack_item.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: feature, neo3, vm

#838 core: move interop to a separate package
  pkg/consensus/consensus.go
  pkg/core/blockchain.go
  pkg/core/blockchainer/blockchainer.go
  pkg/core/gas_price_test.go
  pkg/core/interop/context.go
  pkg/core/interop/enumerator/interop.go
  pkg/core/interop/iterator/interop.go
  pkg/core/interop_neo.go
  pkg/core/interop_neo_test.go
  pkg/core/interop_system.go
  pkg/core/interops.go
  pkg/core/interops_test.go
  pkg/network/blockqueue.go
  pkg/network/server.go
  pkg/rpc/response/result/block.go
  pkg/rpc/response/result/block_header.go
  pkg/rpc/response/result/tx_raw_output.go
  pkg/rpc/response/result/unclaimed.go
  pkg/rpc/response/result/unspents.go
  pkg/rpc/server/server.go
Labels: refactoring

#852 .circleci: enable -coverpkg=all
  .circleci/config.yml
  .travis.yml
  Makefile
  integration/plug.go
Labels: test

#783 Implement Neo.Crypto.* interops
  pkg/compiler/analysis.go
  pkg/compiler/codegen.go
  pkg/compiler/syscall.go
  pkg/compiler/util_test.go
  pkg/compiler/verify_test.go
  pkg/core/interop/crypto/ecdsa.go
  pkg/core/interop_neo.go
  pkg/core/interop_neo_test.go
  pkg/core/interop_system.go
  pkg/core/interops.go
  pkg/crypto/keys/publickey.go
  pkg/crypto/keys/publickey_test.go
  pkg/interop/crypto/crypto.go
  pkg/vm/stack.go
  pkg/vm/stack_test.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: neo3

#855 core: fix typo in TestECDSAVerify
  pkg/core/interop_neo_test.go
Labels: bug

#854 .circleci: count coverage only for cli/ and pkg/
  .circleci/config.yml
  .travis.yml
  Makefile
Labels: test

#844 core: add nonce field to transaction
  cli/wallet/wallet.go
  integration/performance_test.go
  pkg/consensus/block_test.go
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/consensus/payload_test.go
  pkg/consensus/recovery_message_test.go
  pkg/core/block/block_test.go
  pkg/core/blockchain_test.go
  pkg/core/dao/dao_test.go
  pkg/core/helper_test.go
  pkg/core/mempool/mem_pool_test.go
  pkg/core/transaction/claim.go
  pkg/core/transaction/contract.go
  pkg/core/transaction/contract_test.go
  pkg/core/transaction/enrollment.go
  pkg/core/transaction/enrollment_test.go
  pkg/core/transaction/helper_test.go
  pkg/core/transaction/invocation.go
  pkg/core/transaction/issue.go
  pkg/core/transaction/miner.go
  pkg/core/transaction/miner_test.go
  pkg/core/transaction/publish.go
  pkg/core/transaction/register.go
  pkg/core/transaction/register_test.go
  pkg/core/transaction/state.go
  pkg/core/transaction/state_test.go
  pkg/core/transaction/transaction.go
  pkg/core/transaction/transaction_test.go
  pkg/core/util.go
  pkg/core/util_test.go
  pkg/rpc/client/rpc.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/testblocks.acc
Labels: feature, neo3

#856 core: add validUntilBlock field to transaction
  cli/wallet/wallet.go
  pkg/consensus/consensus_test.go
  pkg/consensus/payload_test.go
  pkg/consensus/recovery_message_test.go
  pkg/core/block/block_test.go
  pkg/core/blockchain.go
  pkg/core/blockchain_test.go
  pkg/core/helper_test.go
  pkg/core/transaction/miner_test.go
  pkg/core/transaction/transaction.go
  pkg/core/util_test.go
  pkg/rpc/client/client.go
  pkg/rpc/client/rpc.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/testblocks.acc
Labels: feature, neo3

#859 consensus: added partial message decoding
  pkg/consensus/cache_test.go
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/consensus/payload.go
  pkg/consensus/payload_test.go
  pkg/consensus/recovery_message.go
  pkg/consensus/recovery_message_test.go
Labels: consensus, neo3

#781 Implement Native contract mechanism
  pkg/compiler/for_test.go
  pkg/compiler/struct_test.go
  pkg/compiler/syscall_test.go
  pkg/core/blockchain.go
  pkg/core/blockchainer/blockchainer.go
  pkg/core/dao/dao.go
  pkg/core/interop/runtime/witness.go
  pkg/core/interop_neo.go
  pkg/core/interop_system.go
  pkg/core/interops.go
  pkg/core/native/contract.go
  pkg/core/native/interop.go
  pkg/core/native/native_gas.go
  pkg/core/native/native_neo.go
  pkg/core/native/native_nep5.go
  pkg/core/native_contract_test.go
  pkg/core/state/account.go
  pkg/core/state/native_state.go
  pkg/core/storage/store.go
  pkg/network/helper_test.go
  pkg/smartcontract/call_flags.go
  pkg/smartcontract/manifest/container.go
  pkg/smartcontract/manifest/container_test.go
  pkg/smartcontract/manifest/manifest.go
  pkg/smartcontract/manifest/manifest_test.go
  pkg/smartcontract/manifest/method.go
  pkg/smartcontract/manifest/permission.go
  pkg/smartcontract/manifest/permission_test.go
  pkg/vm/cli/cli.go
  pkg/vm/context.go
  pkg/vm/stack.go
  pkg/vm/stack_item.go
  pkg/vm/stack_item_test.go
  pkg/vm/vm_test.go
Labels: neo3

#862 consensus: partial consensus message decoding
  pkg/consensus/cache_test.go
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/consensus/payload.go
  pkg/consensus/payload_test.go
  pkg/consensus/recovery_message.go
  pkg/consensus/recovery_message_test.go
Labels: consensus

#866 consensus: drop timestamp from outer payload
  pkg/consensus/payload.go
  pkg/consensus/payload_test.go
Labels: consensus, neo3

#857 core,crypto: implement Verifiable interface
  pkg/consensus/block.go
  pkg/consensus/payload.go
  pkg/core/block/block_base.go
  pkg/core/blockchain.go
  pkg/core/helper_test.go
  pkg/core/interop/context.go
  pkg/core/interop/crypto/ecdsa.go
  pkg/core/interop_neo_test.go
  pkg/core/interop_system.go
  pkg/crypto/verifiable.go
Labels: feature, neo3

#868 rpc: add validUntilBlock to transferNEP5
  pkg/rpc/client/nep5.go
Labels: rpc

#887 network: drop checksums from messages
  pkg/network/message.go
Labels: protocol

#874 vm: disallow negative shifts for SHL/SHR
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: vm

#870 core: add sender field to transaction
  cli/wallet/wallet.go
  pkg/consensus/consensus_test.go
  pkg/core/blockchain.go
  pkg/core/blockchain_test.go
  pkg/core/helper_test.go
  pkg/core/native_contract_test.go
  pkg/core/transaction/transaction.go
  pkg/core/util.go
  pkg/core/util_test.go
  pkg/rpc/client/nep5.go
  pkg/rpc/client/rpc.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/request/txBuilder.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/testblocks.acc
Labels: feature, neo3

#897 core,test: move helper functions for testchain to the internal package
  pkg/consensus/consensus_test.go
  pkg/core/helper_test.go
  pkg/internal/testchain/address.go
  pkg/rpc/server/server_test.go
Labels: refactoring

#896 vm: implement new PUSH opcodes
  .docker/wallets/wallet1.json
  .docker/wallets/wallet1_solo.json
  .docker/wallets/wallet2.json
  .docker/wallets/wallet3.json
  .docker/wallets/wallet4.json
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/consensus/payload.go
  pkg/consensus/testdata/wallet1.json
  pkg/consensus/testdata/wallet2.json
  pkg/consensus/testdata/wallet3.json
  pkg/consensus/testdata/wallet4.json
  pkg/core/gas_price_test.go
  pkg/core/helper_test.go
  pkg/core/util.go
  pkg/core/util_test.go
  pkg/crypto/keys/publickey.go
  pkg/crypto/keys/publickey_test.go
  pkg/internal/keytestcases/testcases.go
  pkg/rpc/request/tx_builder_test.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/test_contract.avm
  pkg/rpc/server/testdata/testblocks.acc
  pkg/smartcontract/contract.go
  pkg/vm/context.go
  pkg/vm/contract_checks.go
  pkg/vm/emit/bigint.go
  pkg/vm/emit/emit.go
  pkg/vm/emit/emit_test.go
  pkg/vm/opcode/opcode.go
  pkg/vm/opcode/opcode_string.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
  pkg/wallet/account.go
  pkg/wallet/account_test.go
  pkg/wallet/testdata/wallet1.json
  pkg/wallet/testdata/wallet2.json
  pkg/wallet/wallet_test.go
Labels: feature, neo3, vm

#903 rpc: simplify RPC tests
  pkg/core/helper_test.go
  pkg/internal/testchain/address.go
  pkg/rpc/server/server_test.go
Labels: rpc, test

#901 vm: implement new flow-control opcodes
  pkg/compiler/codegen.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/test_contract.avm
  pkg/rpc/server/testdata/testblocks.acc
  pkg/vm/context.go
  pkg/vm/emit/emit.go
  pkg/vm/opcode/opcode.go
  pkg/vm/opcode/opcode_string.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: compiler, feature, neo3, vm

#907 vm: implement Array/Struct/Map opcodes
  pkg/compiler/codegen.go
  pkg/rpc/request/tx_builder_test.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/test_contract.avm
  pkg/rpc/server/testdata/testblocks.acc
  pkg/vm/context.go
  pkg/vm/opcode/opcode.go
  pkg/vm/opcode/opcode_string.go
  pkg/vm/serialization.go
  pkg/vm/stack_item.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: feature, neo3, vm

#894 core: init native interops in the genesis block
  config/protocol.mainnet.yml
  config/protocol.privnet.docker.four.yml
  config/protocol.privnet.docker.one.yml
  config/protocol.privnet.docker.single.yml
  config/protocol.privnet.docker.three.yml
  config/protocol.privnet.docker.two.yml
  config/protocol.testnet.yml
  config/protocol.unit_testnet.yml
  pkg/config/protocol_config.go
  pkg/consensus/consensus.go
  pkg/core/blockchain.go
  pkg/core/blockchainer/blockchainer.go
  pkg/core/dao/dao.go
  pkg/core/dao/dao_test.go
  pkg/core/helper_test.go
  pkg/core/interop/context.go
  pkg/core/interop_neo.go
  pkg/core/interop_neo_test.go
  pkg/core/interops.go
  pkg/core/interops_test.go
  pkg/core/native/contract.go
  pkg/core/native/interop.go
  pkg/core/native/native_gas.go
  pkg/core/native/native_neo.go
  pkg/core/native/native_nep5.go
  pkg/core/native/validators_count.go
  pkg/core/native_contract_test.go
  pkg/core/state/account.go
  pkg/core/state/account_test.go
  pkg/core/state/native_state.go
  pkg/core/state/validator.go
  pkg/core/state/validator_test.go
  pkg/core/storage/store.go
  pkg/core/storage/store_test.go
  pkg/core/transaction/enrollment.go
  pkg/core/transaction/enrollment_test.go
  pkg/core/transaction/state.go
  pkg/core/transaction/state_descriptor.go
  pkg/core/transaction/state_test.go
  pkg/core/transaction/transaction.go
  pkg/core/transaction/transaction_test.go
  pkg/core/transaction/type.go
  pkg/core/util.go
  pkg/core/util_test.go
  pkg/crypto/keys/publickey.go
  pkg/network/helper_test.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/response/result/account_state.go
  pkg/rpc/response/result/validator.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/testblocks.acc
Labels: neo3

#898 core: change block format to neo3
  go.mod
  go.sum
  pkg/consensus/block.go
  pkg/consensus/block_test.go
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/consensus/payload_test.go
  pkg/consensus/prepare_request.go
  pkg/consensus/prepare_request_test.go
  pkg/consensus/recovery_message_test.go
  pkg/core/block/block.go
  pkg/core/block/block_base.go
  pkg/core/block/block_test.go
  pkg/core/block/consensus_data.go
  pkg/core/block/header_test.go
  pkg/core/blockchain.go
  pkg/core/blockchain_test.go
  pkg/core/helper_test.go
  pkg/core/interop_neo.go
  pkg/core/interop_neo_test.go
  pkg/core/interops.go
  pkg/core/interops_test.go
  pkg/core/mempool/mem_pool_test.go
  pkg/core/native_contract_test.go
  pkg/core/state/nep5.go
  pkg/core/transaction/miner.go
  pkg/core/transaction/miner_test.go
  pkg/core/transaction/transaction.go
  pkg/core/transaction/transaction_test.go
  pkg/core/transaction/type.go
  pkg/core/util.go
  pkg/core/util_test.go
  pkg/network/payload/headers_test.go
  pkg/network/server.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/response/result/block.go
  pkg/rpc/response/result/block_header.go
  pkg/rpc/response/result/nep5.go
  pkg/rpc/response/result/tx_raw_output.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/testblocks.acc
Labels: neo3

#911 vm: implement CONVERT opcode
  pkg/compiler/analysis.go
  pkg/compiler/codegen.go
  pkg/compiler/convert_test.go
  pkg/compiler/return_test.go
  pkg/compiler/struct_test.go
  pkg/consensus/payload.go
  pkg/core/blockchain.go
  pkg/interop/convert/convert.go
  pkg/vm/context.go
  pkg/vm/emit/emit.go
  pkg/vm/opcode/opcode.go
  pkg/vm/opcode/opcode_string.go
  pkg/vm/stack.go
  pkg/vm/stack_item.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: feature, neo3, vm

#917 vm: remove crypto-related opcodes
  pkg/compiler/analysis.go
  pkg/compiler/codegen.go
  pkg/compiler/util_test.go
  pkg/core/gas_price.go
  pkg/core/interop/crypto/hash.go
  pkg/core/interop/crypto/hash_test.go
  pkg/core/interop/crypto/interop.go
  pkg/core/interops.go
  pkg/interop/crypto/crypto.go
  pkg/vm/opcode/opcode.go
  pkg/vm/opcode/opcode_string.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: compiler, neo3, vm

#919 vm: reorder arithmetic and bitwise opcodes
  go.sum
  pkg/compiler/codegen.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/test_contract.avm
  pkg/rpc/server/testdata/testblocks.acc
  pkg/vm/opcode/opcode.go
  pkg/vm/opcode/opcode_string.go
  pkg/vm/stack_item.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: neo3, refactoring, test, vm
