Repository nspcc-dev/neo-go, pull requests merged in 2020-07, with the labels that each got.

#1137 compiler, cli: update ContractCompile and ContractDeploy methods
  cli/smartcontract/smart_contract.go
  pkg/compiler/compiler.go
Labels: compiler, neo3, smartContract

#1139 Fix deployment sysfee and invokes
  cli/smartcontract/smart_contract.go
  pkg/rpc/client/nep5.go
  pkg/rpc/client/policy.go
  pkg/rpc/client/rpc.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/request/txBuilder.go
Labels: bug, rpc

#1138 wallet: marshal script in base64
  .docker/wallets/wallet1.json
  .docker/wallets/wallet1_solo.json
  .docker/wallets/wallet2.json
  .docker/wallets/wallet3.json
  .docker/wallets/wallet4.json
  pkg/consensus/testdata/wallet1.json
  pkg/consensus/testdata/wallet2.json
  pkg/consensus/testdata/wallet3.json
  pkg/consensus/testdata/wallet4.json
  pkg/wallet/account.go
  pkg/wallet/account_test.go
  pkg/wallet/testdata/wallet1.json
  pkg/wallet/testdata/wallet2.json
Labels: wallet

#1145 Cache `transaction.FeePerByte()`
  pkg/core/transaction/transaction.go
  pkg/core/transaction/transaction_test.go
  pkg/rpc/client/rpc_test.go
Labels: feature

#1146 rpc: support stringified address in getnep5balances RPC
  pkg/rpc/request/param.go
  pkg/rpc/request/param_test.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
Labels: bug, rpc

#1147 cli: fixes for contract deployment and invocation
  cli/smartcontract/smart_contract.go
  pkg/rpc/client/nep5.go
  pkg/rpc/client/rpc.go
Labels: bug

#1148 vm: fix stackitem deserialisation
  pkg/rpc/server/server.go
  pkg/vm/stackitem/serialization.go
Labels: bug

#1142 compiler, cli: update manifest.json format
  cli/wallet/nep5.go
  examples/runtime/runtime.go
  examples/storage/storage.go
  examples/token/nep5/nep5.go
  examples/token/token.go
  pkg/compiler/codegen.go
  pkg/compiler/debug.go
  pkg/compiler/debug_test.go
Labels: compiler, neo3

#1156 rpc/request: decode bytearray as base64, fix #1151
  pkg/rpc/request/param.go
  pkg/rpc/request/param_test.go
  pkg/rpc/request/txBuilder.go
  pkg/rpc/request/tx_builder_test.go
Labels: rpc

#1155 Interop and compiler fixes for 3.0
  pkg/compiler/codegen.go
  pkg/compiler/interop_test.go
  pkg/compiler/syscall.go
  pkg/interop/runtime/runtime.go
Labels: compiler

#1162 compiler: compile appcall with dynamic argument
  pkg/compiler/codegen.go
  pkg/compiler/interop_test.go
Labels: compiler, neo3

#1166 Fix struct default init
  pkg/compiler/codegen.go
  pkg/compiler/slice_test.go
  pkg/compiler/struct_test.go
Labels: compiler

#1167 vm: fix INITSSLOT, it's context-wide, not VM-wide
  pkg/vm/context.go
  pkg/vm/json_test.go
  pkg/vm/vm.go
Labels: bug, vm

#1165 core: store NEP5 transfers and balances as big.Int
  pkg/core/blockchain.go
  pkg/core/blockchain_test.go
  pkg/core/blockchainer/blockchainer.go
  pkg/core/helper_test.go
  pkg/core/mempool/feer.go
  pkg/core/mempool/mem_pool.go
  pkg/core/mempool/mem_pool_test.go
  pkg/core/native/native_neo.go
  pkg/core/native/native_nep5.go
  pkg/core/state/nep5.go
  pkg/core/state/nep5_test.go
  pkg/network/helper_test.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_helper_test.go
  pkg/rpc/server/server_test.go
Labels: neo3

#1170 core: prevent concurrent map writes during (*mp).Verify
  pkg/core/mempool/mem_pool.go
  pkg/core/mempool/mem_pool_test.go
Labels: bug, neo3

#1115 keys: support returning legacy verification script
  pkg/crypto/keys/publickey.go
Labels: bug

#1172 Update dbft, add 64-bit timestamps and cv reasons
  go.mod
  go.sum
  pkg/consensus/block.go
  pkg/consensus/change_view.go
  pkg/consensus/change_view_test.go
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/consensus/payload_test.go
  pkg/consensus/prepare_request.go
  pkg/consensus/prepare_request_test.go
  pkg/consensus/recovery_message.go
  pkg/consensus/recovery_message_test.go
  pkg/consensus/recovery_request.go
  pkg/consensus/recovery_request_test.go
  pkg/core/blockchain.go
  pkg/core/blockchainer/blockchainer.go
  pkg/core/native/native_neo.go
  pkg/network/helper_test.go
Labels: consensus

#1177 No free VM runs
  cli/smartcontract/smart_contract.go
  config/protocol.mainnet.yml
  config/protocol.privnet.docker.four.yml
  config/protocol.privnet.docker.one.yml
  config/protocol.privnet.docker.three.yml
  config/protocol.privnet.docker.two.yml
  config/protocol.privnet.yml
  config/protocol.testnet.yml
  config/protocol.unit_testnet.yml
  pkg/consensus/consensus_test.go
  pkg/consensus/payload.go
  pkg/core/blockchain.go
  pkg/core/helper_test.go
  pkg/core/interop/crypto/ecdsa_test.go
  pkg/core/native_policy_test.go
  pkg/core/util.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/testblocks.acc
  pkg/smartcontract/context/context_test.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: bug

#1174 core, compiler: return tx from GetScriptContainer interop
  examples/engine/engine.go
  pkg/compiler/codegen.go
  pkg/core/interop_system.go
Labels: bug, neo3

#1179 rpc: set transaction's script for test invocation
  pkg/rpc/server/server.go
Labels: bug

#1175 crypto: add Secp256k1 support
  .docker/wallets/wallet1.json
  .docker/wallets/wallet1_solo.json
  .docker/wallets/wallet2.json
  .docker/wallets/wallet3.json
  .docker/wallets/wallet4.json
  go.mod
  go.sum
  pkg/compiler/syscall.go
  pkg/compiler/verify_test.go
  pkg/consensus/payload_test.go
  pkg/consensus/testdata/wallet1.json
  pkg/consensus/testdata/wallet2.json
  pkg/consensus/testdata/wallet3.json
  pkg/consensus/testdata/wallet4.json
  pkg/core/interop/crypto/ecdsa.go
  pkg/core/interop/crypto/ecdsa_test.go
  pkg/core/interop/crypto/interop.go
  pkg/core/interop/runtime/witness.go
  pkg/core/interop_neo_test.go
  pkg/core/interop_system.go
  pkg/core/interops.go
  pkg/core/native/native_neo.go
  pkg/core/util_test.go
  pkg/crypto/keys/private_key.go
  pkg/crypto/keys/publickey.go
  pkg/crypto/keys/publickey_test.go
  pkg/crypto/keys/sign_verify_test.go
  pkg/internal/keytestcases/testcases.go
  pkg/interop/crypto/crypto.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/testblocks.acc
  pkg/smartcontract/contract.go
  pkg/smartcontract/contract_test.go
  pkg/vm/contract_checks.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
  pkg/wallet/account_test.go
  pkg/wallet/testdata/wallet1.json
  pkg/wallet/testdata/wallet2.json
  pkg/wallet/wallet_test.go
Labels: neo3

#1169 rpc: adjust RPC calls JSON fields
  .docker/wallets/wallet1.json
  .docker/wallets/wallet1_solo.json
  .docker/wallets/wallet2.json
  .docker/wallets/wallet3.json
  .docker/wallets/wallet4.json
  docs/notifications.md
  pkg/consensus/testdata/wallet1.json
  pkg/consensus/testdata/wallet2.json
  pkg/consensus/testdata/wallet3.json
  pkg/consensus/testdata/wallet4.json
  pkg/core/block/block.go
  pkg/core/test_data/block_1.json
  pkg/core/test_data/block_2.json
  pkg/core/transaction/cosigner.go
  pkg/core/transaction/transaction.go
  pkg/rpc/client/rpc.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/client/wsclient_test.go
  pkg/rpc/response/result/application_log.go
  pkg/rpc/response/result/invoke.go
  pkg/rpc/response/result/nep5.go
  pkg/rpc/response/result/unclaimed_gas.go
  pkg/rpc/response/result/version.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/subscription_test.go
  pkg/smartcontract/manifest/manifest.go
  pkg/smartcontract/manifest/manifest_test.go
  pkg/smartcontract/manifest/method.go
  pkg/wallet/account.go
  pkg/wallet/testdata/wallet1.json
  pkg/wallet/testdata/wallet2.json
Labels: neo3, rpc

#1180 Add calling scripthash check to native nep5 transfers
  pkg/core/interop/context.go
  pkg/core/interop/runtime/witness.go
  pkg/core/interops.go
  pkg/core/native/native_neo.go
  pkg/core/native/native_nep5.go
  pkg/core/native/policy.go
Labels: bug

#1161 network: update CMDUncknown
  pkg/network/message.go
  pkg/network/message_string.go
  pkg/network/payload/inventory.go
  pkg/network/server.go
Labels: neo3, protocol

#1185 network: copy peers for Shutdown iteration
  pkg/network/server.go
Labels: bug

#1187 interop: post-preview2 adjustment
  pkg/compiler/codegen.go
  pkg/compiler/syscall.go
  pkg/core/interop_neo.go
  pkg/core/interop_neo_test.go
  pkg/core/interop_system.go
  pkg/core/interop_system_test.go
  pkg/core/interops.go
  pkg/interop/binary/binary.go
  pkg/interop/blockchain/blockchain.go
  pkg/interop/contract/contract.go
  pkg/smartcontract/manifest/manifest.go
  pkg/smartcontract/manifest/manifest_test.go
  pkg/smartcontract/manifest/method.go
Labels: neo3

#1127 Provide event name in `runtime.Notify`
  examples/engine/engine.go
  examples/runtime/runtime.go
  pkg/compiler/syscall_test.go
  pkg/compiler/vm_test.go
  pkg/core/blockchain.go
  pkg/core/interop/runtime/util.go
  pkg/core/interop_system.go
  pkg/core/interop_system_test.go
  pkg/core/native/native_nep5.go
  pkg/core/state/notification_event.go
  pkg/core/state/notification_event_test.go
  pkg/interop/runtime/runtime.go
  pkg/rpc/response/result/application_log.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/test_contract.avm
  pkg/rpc/server/testdata/testblocks.acc
  pkg/vm/interop.go
Labels: compiler, feature

#1216 rpc: adjust `sendrawtransaction` and `submitblock` RPC calls
  cli/wallet/multisig.go
  cli/wallet/nep5.go
  pkg/rpc/client/nep5.go
  pkg/rpc/client/rpc.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/response/result/relay_result.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
Labels: rpc

#1222 Remove return value count
  pkg/compiler/vm_test.go
  pkg/vm/context.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: vm

#1224 core, vm: remove allowed triggers from syscalls
  pkg/core/interop/context.go
  pkg/core/interops.go
  pkg/vm/interop.go
  pkg/vm/json_test.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: vm

#1232 crypto: fix failing Secp256r1 test
  pkg/core/interop/crypto/ecdsa_test.go
  pkg/core/interop_neo_test.go
  pkg/crypto/keys/private_key.go
  pkg/crypto/keys/sign_verify_test.go
Labels: bug

#1227 cli: implement conversion helpers
  pkg/vm/cli/cli.go
Labels: feature

#1243 network: add uncompressed payload size
  pkg/network/compress.go
Labels: protocol

#1240 Allow to use exported variables and constants
  examples/token/nep5/nep5.go
  examples/token/token.go
  pkg/compiler/analysis.go
  pkg/compiler/codegen.go
  pkg/compiler/compiler.go
  pkg/compiler/debug.go
  pkg/compiler/func_scope.go
  pkg/compiler/global_test.go
  pkg/compiler/testdata/foo/foo.go
  pkg/compiler/testdata/multi/file1.go
  pkg/compiler/testdata/multi/file2.go
  pkg/compiler/testdata/strange/normal.go
  pkg/compiler/vm_test.go
Labels: compiler

#1217 rpc: return transfers for migrated contracts
  pkg/core/blockchain.go
  pkg/core/blockchainer.go
  pkg/core/dao/dao.go
  pkg/core/helper_test.go
  pkg/core/interop_neo.go
  pkg/core/state/nep5.go
  pkg/core/storage/store.go
  pkg/network/helper_test.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/test_contract.avm
  pkg/rpc/server/testdata/test_contract.go
  pkg/rpc/server/testdata/testblocks.acc
Labels: bug, rpc
