Repository nspcc-dev/neo-go, pull requests merged in 2021-08, with the labels that each got.

#2115 network: fix Ping messages
  pkg/network/server.go
Labels: bug

#2116 network: fix Ping messages
  pkg/network/server.go
Labels: bug

#2126 core: take an addblock lock on exit
  pkg/core/blockchain.go
Labels: bug

#2135 cli: fix tests for go1.17
  cli/server/dump_test.go
Labels: test

#2148 Another round of VM microoptimizations
  pkg/core/interop/contract/call.go
  pkg/core/interop/crypto/ecdsa.go
  pkg/core/interop/iterator/interop.go
  pkg/core/interop/runtime/engine.go
  pkg/core/interop/runtime/util.go
  pkg/core/interop/runtime/witness.go
  pkg/core/interop_system.go
  pkg/core/native/interop.go
  pkg/vm/context.go
  pkg/vm/stack.go
  pkg/vm/vm.go
Labels: vm
