Repository nspcc-dev/neo-go, pull requests merged in 2021-03, with the labels that each got.

#1785 Process `return` in inlined functions properly.
  pkg/compiler/codegen.go
  pkg/compiler/inline.go
  pkg/compiler/inline_test.go
  pkg/compiler/vm_test.go
Labels: bug, compiler

#1801 consensus/test: add missing `t.Cleanup()`
  pkg/consensus/consensus_test.go
Labels: bug, test

#1805 interop: fix ConvertContextToReadOnly interop
  pkg/interop/storage/storage.go
Labels: bug

#1806 core/test: fix parameter count for `CreateMultisigAccount`
  pkg/core/interops.go
Labels: bug

#1808 compiler: fix import alias handling
  pkg/compiler/analysis.go
  pkg/compiler/codegen.go
  pkg/compiler/import_test.go
Labels: bug, compiler

#1796 Add syscalls for POW and SQRT opcodes
  pkg/compiler/analysis.go
  pkg/compiler/codegen.go
  pkg/compiler/constant_test.go
  pkg/compiler/convert_test.go
  pkg/compiler/syscall_test.go
  pkg/interop/contract/contract.go
  pkg/interop/convert/convert.go
  pkg/interop/math/math.go
  pkg/interop/neogointernal/opcode.go
  pkg/interop/runtime/runtime.go
  pkg/interop/storage/storage.go
Labels: compiler

#1809 compiler: add test for syscall handling
  pkg/compiler/syscall_test.go
  pkg/core/interops.go
  pkg/interop/contract/contract.go
Labels: compiler

#1822 Convert boolean values in `vm/emit`
  cli/nep17_test.go
  cli/testdata/wallet1_solo.json
  pkg/compiler/binary_expr_test.go
  pkg/compiler/for_test.go
  pkg/compiler/import_test.go
  pkg/core/helper_test.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/testblocks.acc
  pkg/rpc/server/testdata/verification_contract.go
  pkg/vm/emit/emit.go
  pkg/vm/emit/emit_test.go
Labels: bug

#1832 consensus: add MaxBlockSize and MaxBlockSysFee settings
  pkg/config/protocol_config.go
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/core/block/block.go
  pkg/core/block/block_test.go
  pkg/core/blockchain.go
  pkg/network/server.go
Labels: consensus

#1838 Extend RPC client
  pkg/rpc/client/native.go
  pkg/rpc/client/policy.go
  pkg/rpc/client/rpc_test.go
Labels: rpc

#1825 rpc: refactor invokecontractverify
  internal/fakechain/fakechain.go
  pkg/core/blockchain.go
  pkg/core/blockchainer/blockchainer.go
  pkg/core/helper_test.go
  pkg/rpc/request/txBuilder.go
  pkg/rpc/request/tx_builder_test.go
  pkg/rpc/server/client_test.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/testblocks.acc
  pkg/rpc/server/testdata/verification_with_args_contract.go
Labels: bug

#1839 core: fix transaction hashes
  cli/testdata/chain50x2.acc
  pkg/core/block/block_test.go
  pkg/core/blockchain_test.go
  pkg/core/helper_test.go
  pkg/core/transaction/helper_test.go
  pkg/core/transaction/transaction.go
  pkg/core/transaction/transaction_test.go
  pkg/crypto/verifiable.go
  pkg/rpc/client/rpc_test.go
  pkg/rpc/client/wsclient_test.go
  pkg/rpc/server/server_test.go
  pkg/rpc/server/testdata/testblocks.acc
  pkg/smartcontract/context/context.go
Labels: bug

#1840 consensus: fix panic during verifyBlock
  pkg/consensus/consensus.go
Labels: bug

#1843 Documentation update and microfixes
  Makefile
  README.md
  config/protocol.testnet.yml
  docs/cli.md
  docs/consensus.md
  docs/rpc.md
  pkg/compiler/doc.go
  pkg/compiler/native_test.go
  pkg/config/doc.go
  pkg/config/netmode/doc.go
  pkg/config/netmode/netmode.go
  pkg/consensus/doc.go
  pkg/core/block/doc.go
  pkg/core/interop/doc.go
  pkg/core/native/doc.go
  pkg/core/transaction/doc.go
  pkg/crypto/doc.go
  pkg/crypto/hash/doc.go
  pkg/crypto/keys/doc.go
  pkg/encoding/address/doc.go
  pkg/encoding/bigint/doc.go
  pkg/encoding/fixedn/doc.go
  pkg/interop/math/math.go
  pkg/interop/native/crypto/crypto.go
  pkg/interop/native/gas/gas.go
  pkg/interop/native/ledger/ledger.go
  pkg/interop/native/management/management.go
  pkg/interop/native/nameservice/name_service.go
  pkg/interop/native/neo/neo.go
  pkg/interop/native/notary/notary.go
  pkg/interop/native/oracle/oracle.go
  pkg/interop/native/policy/policy.go
  pkg/interop/native/roles/roles.go
  pkg/interop/native/std/std.go
  pkg/interop/neogointernal/doc.go
Labels: documentation

#1850 core: fix storage.Put price
  pkg/core/interop_system.go
  pkg/core/interops.go
Labels: bug

#1869 core: RC1 states dumps compatibility fixes
  pkg/core/native/native_neo.go
  scripts/compare-dumps.go
  scripts/compare-dumps_test.go
Labels: bug

#1874 vm: minor C# compatibility fixes
  pkg/core/interop/runtime/engine.go
  pkg/core/interop/runtime/engine_test.go
  pkg/vm/vm.go
Labels: bug
