Repository nspcc-dev/neo-go, pull requests merged in 2021-07, with the labels that each got.

#2034 Fix MPT branch node strip after deletion
  pkg/core/mpt/batch.go
  pkg/core/mpt/batch_test.go
  pkg/core/native/native_nep17.go
Labels: bug

#2047 Don't create an extension node for the last branch child
  pkg/core/mpt/batch.go
  pkg/core/mpt/batch_test.go
  pkg/core/mpt/trie.go
  pkg/core/mpt/trie_test.go
Labels: bug

#2052 vm: copy integers for unary operations, fix #2051
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: bug, vm

#2072 rpc/request: support passing accounts as addresses
  pkg/rpc/request/param.go
  pkg/rpc/request/param_test.go
Labels: bug, rpc

#2076 Improve temp file/dir handling in tests
  cli/contract_test.go
  cli/dump_test.go
  cli/multisig_test.go
  cli/nep11_test.go
  cli/nep17_test.go
  cli/wallet_test.go
  pkg/core/stateroot_test.go
  pkg/core/storage/boltdb_store_test.go
  pkg/vm/cli/cli_test.go
Labels: test

#2083 consensus: fix nonce handling
  go.mod
  go.sum
  pkg/consensus/block.go
  pkg/consensus/consensus.go
Labels: consensus

#2092 Fix C# signing context compatibility
  cli/paramcontext/context.go
  pkg/smartcontract/context/context.go
  pkg/smartcontract/context/context_test.go
  pkg/smartcontract/context/item.go
  pkg/smartcontract/parameter.go
Labels: bug

#2099 wallet: truncate file after writing
  cli/wallet_test.go
  pkg/wallet/wallet.go
Labels: bug

#2097 docs/compiler.md: document contract configuration
  docs/compiler.md
Labels: documentation
