Repository nspcc-dev/neo-go, pull requests merged in 2022-05, with the labels that each got.

#2466 Rules scope fixes
  pkg/core/transaction/witness_condition.go
  pkg/core/transaction/witness_scope.go
  pkg/core/transaction/witness_scope_string.go
  pkg/network/message_string.go
  pkg/rpc/server/server.go
Labels: bug

#2472 rpc: move latest getversion compat to 0.98.3
  pkg/rpc/response/result/version.go
  pkg/rpc/response/result/version_test.go
  pkg/rpc/server/server_helper_test.go
  pkg/rpc/server/server_test.go
Labels: rpc

#2475 vm: check instruction offset is valid before subsequent IP move
  pkg/vm/context.go
Labels: bug

#2488 neo: mint GAS after NEO transfer processing
  CHANGELOG.md
  pkg/core/native/native_gas.go
  pkg/core/native/native_neo.go
  pkg/core/native/native_nep17.go
  pkg/core/native/native_test/neo_test.go
Labels: bug

#2498 Fix some refcounter issues
  pkg/vm/opcodebench_test.go
  pkg/vm/ref_counter.go
  pkg/vm/ref_counter_test.go
  pkg/vm/slot.go
  pkg/vm/slot_test.go
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: bug, vm

#2499 core: avoid concurrent map iteration and map write during SeekAsync over private MemCachedStore
  pkg/core/interop_system.go
  pkg/core/native/native_neo.go
Labels: bug
