Repository nspcc-dev/neo-go, pull requests merged in 2022-03, with the labels that each got.

#2390 Revert "Makefile: add `unsupported` to docker windows image tag and b…
  Makefile
Labels: windows

#2391 vm: fix integer conversions
  pkg/vm/vm.go
  pkg/vm/vm_test.go
Labels: vm

#2396 Return error on negative instruction pointer in `Context.Next`
  pkg/vm/context.go
  pkg/vm/vm_test.go
Labels: bug, vm, fuzz

#2397 vm: avoid panic in `IsScriptCorrect`
  pkg/vm/contract_checks.go
  pkg/vm/contract_checks_test.go
Labels: bug, vm, fuzz

#2404 Fix log entries with user input
  pkg/rpc/server/prometheus.go
  pkg/rpc/server/server.go
  pkg/rpc/server/server_test.go
Labels: bug

#2409 network: check compressed payload size in `decompress`
  pkg/network/compress.go
  pkg/network/fuzz_test.go
  pkg/network/message_test.go
Labels: bug, fuzz
