Repository nspcc-dev/neo-go, pull requests merged in 2023-10, with the labels that each got.

#3147 compiler: Fix emitting big uint64 constants
  pkg/compiler/codegen.go
  pkg/compiler/numeric_test.go
Labels: bug, compiler

#3148 storage: Use timeout for boltdb database opening
  pkg/core/storage/boltdb_store.go
Labels: enhancement

#3110 Fix race caused by design of native Neo validators/committee cache
  pkg/consensus/consensus.go
  pkg/core/blockchain.go
  pkg/core/blockchain_core_test.go
  pkg/core/native/native_neo.go
  pkg/core/native/native_test/neo_test.go
Labels: bug

#3153 .github: upgrade coverage uploading action
  .github/workflows/tests.yml
Labels: test

#3168 Introduce Genesis protocol setting extensions
  docs/node-configuration.md
  pkg/config/genesis_extensions.go
  pkg/config/hardfork_string.go
  pkg/config/protocol_config.go
  pkg/config/protocol_config_test.go
  pkg/core/blockchain.go
  pkg/core/blockchain_neotest_test.go
  pkg/core/helper_test.go
  pkg/core/native/contract.go
  pkg/core/native/designate.go
  pkg/core/native/native_test/designate_test.go
  pkg/core/native/noderoles/role.go
  pkg/core/native/noderoles/role_string.go
  pkg/core/native/noderoles/role_test.go
  pkg/core/native/noderoles/roles.go
  pkg/core/native_designate_test.go
  pkg/core/transaction/witness_scope_string.go
  pkg/core/transaction/witnessconditiontype_string.go
  pkg/core/util.go
  pkg/core/util_test.go
  pkg/crypto/keys/publickey.go
  pkg/crypto/keys/publickey_test.go
  pkg/network/message_string.go
Labels: enhancement
