Repository nspcc-dev/neo-go, pull requests merged in 2023-11, with the labels that each got.

#3199 neorpc: adjust common error messages
  pkg/neorpc/errors.go
  pkg/rpcclient/rpc_test.go
  pkg/rpcclient/wsclient_test.go
  pkg/services/rpcsrv/server_test.go
Labels: rpc

#3203 docs: adjust ValidatorsHistory documentation
  docs/node-configuration.md
Labels: documentation

#3194 manifest: add compatibility test for Permissions and Trust serialization
  pkg/smartcontract/manifest/manifest_test.go
Labels: test

#3186 Restrict maximum serialized NEF file size
  cli/smartcontract/contract_test.go
  pkg/compiler/compiler_test.go
  pkg/core/state/contract.go
  pkg/smartcontract/nef/nef.go
  pkg/smartcontract/nef/nef_test.go
Labels: smartContract, enhancement, cli

#3207 rpcsrv/params: limit tx signers/witnesses
  pkg/services/rpcsrv/params/param.go
  pkg/services/rpcsrv/params/param_test.go
Labels: bug, rpc

#3211 core: review usages of (*intero.Context).BlockHeight method
  docs/notary.md
  pkg/core/interop/context.go
  pkg/core/interop/contract/account_test.go
  pkg/core/interop/runtime/ext_test.go
  pkg/core/native/designate.go
  pkg/core/native/interop.go
  pkg/core/native/native_test/gas_test.go
  pkg/core/native/native_test/notary_test.go
  pkg/core/native/notary.go
  pkg/services/rpcsrv/server.go
Labels: bug

#3214 docs: canceltransaction is not going to be supported
  docs/rpc.md
  pkg/rpcclient/doc.go
Labels: documentation, rpc

#3232 interop: add contract storage limits
  examples/engine/go.mod
  examples/engine/go.sum
  examples/events/go.mod
  examples/events/go.sum
  examples/iterator/go.mod
  examples/iterator/go.sum
  examples/nft-d/go.mod
  examples/nft-d/go.sum
  examples/nft-nd-nns/go.mod
  examples/nft-nd-nns/go.sum
  examples/nft-nd/go.mod
  examples/nft-nd/go.sum
  examples/oracle/go.mod
  examples/oracle/go.sum
  examples/runtime/go.mod
  examples/runtime/go.sum
  examples/storage/go.mod
  examples/storage/go.sum
  examples/timer/go.mod
  examples/timer/go.sum
  examples/token/go.mod
  examples/token/go.sum
  examples/zkp/cubic_circuit/go.mod
  examples/zkp/cubic_circuit/go.sum
  examples/zkp/xor_compat/go.mod
  examples/zkp/xor_compat/go.sum
  go.mod
  go.sum
  internal/contracts/oracle_contract/go.mod
  internal/contracts/oracle_contract/go.sum
  pkg/compiler/native_test.go
  pkg/interop/storage/limits.go
Labels: smartContract

#3237 vm: allow to emit `any` based on its type
  pkg/vm/emit/emit.go
Labels: vm

#3242 Improve notification subsystem documentation
  docs/notifications.md
  pkg/rpcclient/wsclient.go
Labels: documentation

#3240 core: remove UpdateHistory from NativeContract structure
  pkg/core/state/contract.go
Labels: bug
