Repository nspcc-dev/neo-go, pull requests merged in 2024-11, with the labels that each got.

#3661 services/rpcsrv: Return a new server by pointer
  cli/server/server.go
  internal/testcli/executor.go
  pkg/services/rpcsrv/server.go
  pkg/services/rpcsrv/server_helper_test.go
Labels: bug, rpc

#3663 io: specify Bytes() behavior a bit better for BufBinWriter
  pkg/io/binaryBufWriter.go
Labels: documentation, enhancement

#3666 Tiny documentation improvements
  pkg/rpcclient/rpc.go
  pkg/vm/emit/emit.go
Labels: documentation, enhancement

#3678 *: fix some dupword warnings
  pkg/compiler/compiler.go
  pkg/core/blockchain.go
  pkg/core/mempool/mem_pool.go
  pkg/rpcclient/nep11/divisible.go
  pkg/services/rpcsrv/params/types.go
  pkg/vm/stackitem/item.go
Labels: documentation, enhancement

#3683 Improve tx and block doc
  pkg/core/block/block.go
  pkg/core/block/header.go
  pkg/core/transaction/transaction.go
Labels: documentation, enhancement

#3677 vm: make slots public
  ROADMAP.md
  cli/vm/cli.go
  pkg/vm/context.go
  pkg/vm/json_test.go
  pkg/vm/slot.go
  pkg/vm/slot_test.go
  pkg/vm/vm.go
Labels: vm

#3688 vm: fix incorrect refcounting in POPITEM
  pkg/vm/ref_counter_test.go
  pkg/vm/vm.go
Labels: bug, vm, U1

#3687 Extend smartcontract type conversions
  pkg/io/size.go
  pkg/rpcclient/invoker/invoker_test.go
  pkg/smartcontract/parameter.go
  pkg/smartcontract/parameter_test.go
Labels: enhancement

#3710 Dockerfile: migrate to AS keyword usage
  Dockerfile
  Dockerfile.wsc
Labels: bug

#3711 go.mod: upgrade dBFT version
  go.mod
  go.sum
  pkg/consensus/block.go
  pkg/consensus/block_test.go
  pkg/consensus/consensus.go
  pkg/consensus/consensus_test.go
  pkg/consensus/crypto.go
  pkg/consensus/crypto_test.go
  pkg/consensus/payload.go
  pkg/consensus/payload_test.go
  pkg/consensus/recovery_message_test.go
Labels: consensus, dependencies

#3713 config: enable NeoFSBlockFetcher by default
  config/protocol.mainnet.neofs.yml
  config/protocol.mainnet.yml
  config/protocol.testnet.neofs.yml
  config/protocol.testnet.yml
Labels: config
