Repository nspcc-dev/neo-go, pull requests merged in 2024-07, with the labels that each got.

#3501 Add a missing `mptdata` test
  pkg/network/payload/mptdata_test.go
Labels: test, U4, S4, I4

#3504 config: get back default node configuration values
  pkg/config/config.go
Labels: bug, I3, U4, S4

#3534 Fix missing block field
  cli/smartcontract/testdata/rpcbindings/structs/rpcbindings.out
  cli/smartcontract/testdata/rpcbindings/structs/rpcbindings_dynamic_hash.out
  examples/engine/go.mod
  examples/engine/go.sum
  examples/events/go.mod
  examples/events/go.sum
  examples/iterator/go.mod
  examples/iterator/go.sum
  examples/nft-d/go.mod
  examples/nft-d/go.sum
  examples/nft-nd-nns/go.mod
  examples/nft-nd-nns/go.sum
  examples/nft-nd/go.mod
  examples/nft-nd/go.sum
  examples/oracle/go.mod
  examples/oracle/go.sum
  examples/runtime/go.mod
  examples/runtime/go.sum
  examples/storage/go.mod
  examples/storage/go.sum
  examples/timer/go.mod
  examples/timer/go.sum
  examples/token/go.mod
  examples/token/go.sum
  examples/zkp/cubic_circuit/go.mod
  examples/zkp/cubic_circuit/go.sum
  examples/zkp/xor_compat/go.mod
  examples/zkp/xor_compat/go.sum
  go.mod
  go.sum
  internal/contracts/oracle_contract/go.mod
  internal/contracts/oracle_contract/go.sum
  pkg/core/block/block.go
  pkg/core/native/native_test/ledger_test.go
  pkg/interop/native/ledger/block.go
Labels: bug
