Repository nspcc-dev/neo-go, pull requests merged in 2024-12, with the labels that each got.

#3722 config: enable hardforks for default NeoFS testnet config
  config/protocol.testnet.neofs.yml
Labels: bug, config

#3737 services: fix timer draining
  pkg/services/rpcsrv/server.go
Labels: bug, rpc

#3750 RemoveUntraceableHeaders
  docs/node-configuration.md
  pkg/config/ledger_config.go
  pkg/core/blockchain.go
  pkg/core/blockchain_core_test.go
  pkg/core/dao/dao.go
  pkg/core/dao/dao_test.go
  pkg/network/server.go
Labels: I3, U3, enhancement, S4

#3725 *: update `neofs-sdk-go`
  cli/util/upload_bin.go
  go.mod
  go.sum
  pkg/services/blockfetcher/blockfetcher.go
  pkg/services/helpers/neofs/blockstorage.go
  scripts/go.mod
  scripts/go.sum
Labels: dependencies

#3765 zkp: bump golang.org/x/crypto from 0.26.0 to 0.31.0
  examples/zkp/cubic_circuit/go.mod
  examples/zkp/cubic_circuit/go.sum
Labels: dependencies
